project_id = "axoqjwvqxgtzsdmlmnbv"

[functions.test-ai-model]
verify_jwt = true

[functions.generate-social-post]
verify_jwt = true

[functions.generate-article]
verify_jwt = true

[functions.grant-admin]
verify_jwt = false