project_id = "axoqjwvqxgtzsdmlmnbv"

[functions.test-ai-model]
verify_jwt = true

[functions.generate-social-post]
verify_jwt = true

[functions.generate-article]
verify_jwt = true

[functions.publish-article-to-social]
verify_jwt = false

[functions.test-article-webhook]
verify_jwt = true

[functions.sitemap]
verify_jwt = false