name = "plain-page-link"
compatibility_date = "2024-10-31"
pages_build_output_dir = "dist"

[build]
command = "npm run build"

[build.upload]
format = "directory"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]
fallthrough = true
